version: '3.2'
services:
    web:
        image: node:lts-buster
        container_name: node14
        volumes:
            - ./:/root/myapp
        ports:
            - "3000:3000"
        depends_on:
            - mysql
        command: /bin/bash -c "npm install && yarn start"
    mysql:
        image: mysql:latest
        container_name: mysqldatabase
        ports:
            - "3306:3306"
        volumes:
            - ./.db_data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
