version: '3.2'
services:
    web:
        image: node:14.20.0-buster-slim
        container_name: node14
        volumes:
            - ./:/home/node/app
        ports:
            - "5000:3000"
        working_dir: /home/node/app
        depends_on:
            - mysql
        tty: true
        command: npm install && npm run dev
    mysql:
        image: mysql:5.7.39-debian
        container_name: mysqldatabase
        ports:
            - "3306:33066"
        volumes:
            - ./.docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: 2j/g6ru4cj84
            
